Lambton eftpos
LB-Kisok1 Workstation ID, TerminalID the same???? cause problem

12sa shelf settings Email support. 120000 delay
Anu Sharma 22300007530135 NEW MONITOR ACCOUNT - emailed
CHECK DINO EXHIBIT PRICING - emailed
WD1 MONITOR KIOSK NOT CREDITING PATRONS, WHO AND WHEN? - logged
EMAIL CARA RE LEAVE - emailed

MAYFIELD HOLDS

SMS WORDING TEST WHEN UPDATED

3D PRINTER-MOVE TO 1ST FLOOR, PRINT. IS IT ON SAME CIRCUIT AS MONITOR KIOSK??


TAFE PUBLIC PCs